Repository bondrnk/group-project, pull requests merged in 2021-10, with the labels that each got.

#47 #33 fix navigation
  about-us.css
  index.css
  index.html
  index.js
  scss/components/_banner.scss
  scss/components/_footer.scss
  scss/components/_header.scss
  scss/components/_index.scss
  scss/components/_navigation.scss
  scss/components/_section-advantages.scss
  src/_includes/components/banner.pug
  src/_includes/components/footer.pug
  src/_includes/components/header.pug
  src/_includes/components/navigation.pug
  src/_includes/components/section-contact-us.pug
  src/_includes/elements/logo.pug
Labels: bug

#48 #2 create basic components elements part 2
  about-us.css
  about-us.html
  about-us.pug
  assets/images/banner1.jpg
  assets/images/banner2.jpg
  assets/images/banner3.jpg
  assets/images/banner4.jpg
  index.css
  index.html
  index.pug
  scss/_variables.scss
  scss/components/_banner.scss
  scss/components/_header.scss
  scss/elements/_link.scss
  scss/elements/_social-link.scss
  src/_includes/components/banner.pug
  src/_includes/components/footer.pug
  src/_includes/components/index.pug
  src/_includes/components/navigation.pug
  src/_includes/components/section-banner-adventure.pug
  src/_includes/components/section-banner-home-start.pug
  src/_includes/components/section-banner-info-covid.pug
  src/_includes/components/section-contact-us.pug
  src/_includes/components/section-establishment.pug
  src/_includes/components/section-services.pug
  src/_includes/elements/link.pug
Labels: bug

#46 #12 section services
  about-us.css
  about-us.pug
  index.css
  index.html
  index.pug
  scss/components/_banner.scss
  scss/components/_index.scss
  scss/components/_section-advantages.scss
  scss/components/_section-establishment.scss
  scss/components/_section-services.scss
  scss/components/_service-card.scss
  src/_includes/components/banner-adventure.pug
  src/_includes/components/banner-home-start.pug
  src/_includes/components/banner-info-covid.pug
  src/_includes/components/index.pug
  src/_includes/components/section-services.pug
  src/_includes/components/service-card.pug
Labels: home page

#45 #16 about authors
  about-us.css
  about-us.html
  about-us.pug
  assets/img/alex.png
  assets/img/ann.png
  assets/img/boy02.png
  assets/img/dmytro.png
  assets/img/girl01.png
  assets/img/pavlo.png
  assets/img/sergii.png
  assets/img/shtepa+.png
  assets/img/tatjana.png
  assets/img/vitalii.png
  index.css
  index.html
  index.js
  scss/_variables.scss
  scss/components/_banner-contact-us.scss
  scss/components/_banner.scss
  scss/components/_index.scss
  scss/components/_loading.scss
  scss/components/_section-about-us.scss
  scss/components/_section-contact-us.scss
  scss/components/_service-card.scss
  scss/elements/_icon.scss
  scss/elements/_index.scss
  scss/elements/_photocard.scss
  scss/plugins/_index.scss
  scss/plugins/_simptip.scss
  src/_extends/common.pug
  src/_includes/components/banner-contact-us.pug
  src/_includes/components/banner.pug
  src/_includes/components/header.pug
  src/_includes/components/index.pug
  src/_includes/components/section-about-us.pug
  src/_includes/components/section-advantages.pug
  src/_includes/components/service-card.pug
  src/_includes/elements/icon.pug
  src/_includes/elements/index.pug
  src/_includes/elements/photocard.pug
Labels: about-us page

#50 fixed photo
  about-us.css
  about-us.html
  index.css
  scss/components/_banner.scss
  src/_includes/components/banner-contact-us.pug
  src/_includes/components/section-about-us.pug
Labels: bug

#60 #69 add variables and animation
  about-us.css
  about-us.html
  about-us.pug
  assets/fonts/Source-Pro/SourceSansPro-Bold.ttf
  assets/photos/Anasteisha.png
  assets/photos/Beetroot-Logo.png
  assets/photos/Dimooooon.png
  assets/photos/Oleksiychuk.jpg
  assets/photos/Pavlentiy.png
  assets/photos/SerGO.png
  assets/photos/Tanuffka.png
  assets/photos/alex.png
  assets/photos/ann.png
  assets/photos/dmytro.png
  assets/photos/pavlo.png
  assets/photos/sergii.png
  assets/photos/tatjana.png
  index.css
  index.html
  scss/_fonts.scss
  scss/_keyframes.scss
  scss/_main.scss
  scss/_variables.scss
  scss/components/_banner.scss
  scss/components/_footer.scss
  scss/components/_section-about-us.scss
  scss/components/_section-advantages.scss
  scss/components/_section-services.scss
  scss/components/_service-card.scss
  scss/elements/_burger-menu.scss
  scss/elements/_form-pop-up.scss
  scss/elements/_index.scss
  scss/elements/_photocard.scss
  src/_includes/components/section-about-us.pug
  src/_includes/components/section-advantages.pug
  src/_includes/components/section-services.pug
  src/_includes/components/service-card.pug
  src/_includes/elements/form-pop-up.pug
  src/_includes/elements/index.pug
  src/_includes/elements/photocard.pug
Labels: bug

#61 #69 add variables and animation
  about-us.html
  assets/photos/Anasteisha.jpg
  assets/photos/Anasteisha.png
  assets/photos/Dimooooon.jpg
  assets/photos/Dimooooon.png
  assets/photos/Pavlentiy.jpg
  assets/photos/Pavlentiy.png
  assets/photos/SerGO.jpg
  assets/photos/SerGO.png
  assets/photos/Tanuffka.jpg
  assets/photos/Tanuffka.png
  assets/photos/shtepa.jpg
  assets/photos/shtepa.png
  assets/photos/vitalii.jpg
  assets/photos/vitalii.png
  src/_includes/components/section-about-us.pug
Labels: bug
