Repository bondrnk/group-project, pull requests merged in 2021-09, with the labels that each got.

#11 # 1 create basic components part 1
  .gitignore
  assets/icon/logo/logo.svg
  index.css
  index.html
  index.pug
  scss/_main.scss
  scss/_variables.scss
  scss/components/_header.scss
  scss/components/_navigation.scss
  scss/elements/_link.scss
  scss/elements/_logo.scss
  src/_includes/components/header.pug
  src/_includes/components/navigation.pug
  src/_includes/elements/logo.pug
  wiki/images/#5 create basic layout #10.png
  wiki/images/Create basic layout.png
  wiki/images/Reviewers.png
Labels: home page

#20 #1 part 1 logo and elemetnts
  .gitignore
  assets/icon/common/symbol-defs.svg
  assets/icon/logo/logo.svg
  index.css
  index.html
  scss/components/_header.scss
  scss/components/_navigation.scss
  scss/elements/_icon.scss
  scss/elements/_image.scss
  scss/elements/_index.scss
  scss/elements/_link.scss
  scss/elements/_logo.scss
  src/_includes/components/header.pug
  src/_includes/elements/icon.pug
  src/_includes/elements/image.pug
  src/_includes/elements/index.pug
  src/_includes/elements/logo.pug
Labels: bug

#39 #35 add loading page (bug)
  scss/components/_loading.scss
Labels: bug

#40 Fixed fonts, loading, simptip
  about-us.css
  index.css
  index.html
  scss/_fonts.scss
  scss/components/_loading.scss
  scss/plugins/_index.scss
  scss/plugins/_simptip.scss
  src/_extends/common.pug
Labels: bug

#41 #35 fixed loading (part 2)
  about-us.css
  index.css
  scss/components/_loading.scss
Labels: bug

#34 #14 add section advantages
  about-us.css
  index.css
  index.html
  index.pug
  scss/components/_index.scss
  scss/components/_section-advantages.scss
  src/_includes/components/index.pug
  src/_includes/components/section-advantages.pug
Labels: about-us page

#38 #17 part 1 logo and elemetnts
  about-us.css
  about-us.html
  about-us.pug
  assets/icon/common/symbol-defs.svg
  assets/images/section-contact-us.jpg
  index.css
  index.html
  index.pug
  package-lock.json
  package.json
  scss/_keyframes.scss
  scss/_main.scss
  scss/_variables.scss
  scss/components/_banner.scss
  scss/components/_footer.scss
  scss/components/_header.scss
  scss/components/_index.scss
  scss/components/_loading.scss
  scss/components/_navigation.scss
  scss/components/_section-contact-us.scss
  scss/elements/_icon.scss
  scss/elements/_link.scss
  scss/elements/_logo.scss
  scss/index.scss
  src/_includes/components/banner.pug
  src/_includes/components/footer.pug
  src/_includes/components/header.pug
  src/_includes/components/index.pug
  src/_includes/components/navigation.pug
  src/_includes/components/section-contact-us.pug
  src/_includes/elements/index.pug
  src/_includes/elements/logo.pug
Labels: bug
